export const facts = [
  "Kenya's Great Rift Valley stretches over 6,000 kilometres across Africa and is visible from space.",
  "The word 'benga' -- the genre that defined Kenyan pop music -- originally meant something that bounced or vibrated in Luo.",
  "Wangari Maathai, the first African woman to win the Nobel Peace Prize, facilitated the planting of over 51 million trees across Kenya.",
  "The Swahili coast was trading with Arabia, India, and China over a thousand years before European contact.",
  "Kenya's marathon dominance began in the Nandi Hills, where altitude, culture, and terrain combined to produce the world's greatest distance runners.",
  "The 1982 coup attempt against President Moi lasted less than 12 hours but led to Kenya becoming a de jure one-party state.",
  "M-Pesa, launched in 2007, was the world's first mobile money system and now processes more transactions than Western Union globally.",
  "During the Mau Mau emergency, the British detained over 150,000 Kenyans -- a scale of detention not seen in any other British colonial conflict.",
  "The Kenya-Uganda railway, nicknamed the 'Lunatic Express,' was built between 1896-1901 at a cost of 2,500 Indian labourers' lives.",
  "Jomo Kenyatta's 1938 anthropological study 'Facing Mount Kenya' was one of the first African ethnographies written by an African scholar.",
  "The Maasai Mara is named after the Maasai people and the Mara River, which means 'spotted' in Maa -- referring to the way trees dot the landscape.",
  "Dedan Kimathi, the last Mau Mau field marshal, was captured in 1956 and executed in 1957. His body has never been returned to his family.",
  "The Sultan of Zanzibar controlled a 10-mile coastal strip of Kenya until 1963, when it was ceded to the new Kenyan government.",
  "Kenya's national anthem was composed by a commission of five Kenyans in 1963, based on a traditional Pokomo lullaby.",
  "The Turkana Basin has produced some of the oldest evidence of human ancestors -- fossils dating back over 4 million years.",
  "Ngugi wa Thiong'o, Kenya's most famous living writer, has been writing exclusively in Gikuyu since 1977 to decolonize African literature.",
  "Tom Mboya, one of Kenya's brightest political minds, was assassinated in 1969 on Government Road in Nairobi. His killer was hanged; the motive remains disputed.",
  "The Battle of Garissa in 1963 saw Somali shifta rebels attack a Kenyan police post, sparking a five-year conflict that shaped Kenya's northern frontier.",
  "Kapenguria, a remote town in West Pokot, became famous as the site where Jomo Kenyatta and five others were tried during the State of Emergency.",
  "Lake Turkana, the world's largest permanent desert lake, was called Lake Rudolf until 1975, when it was renamed after independence.",
  "The Lamu Archipelago has been continuously inhabited for over 700 years and remains one of the oldest Swahili settlements in East Africa.",
  "Kisumu, Kenya's third-largest city, was originally called Port Florence after the wife of a railway engineer.",
  "The Mau Mau oath was administered in secret ceremonies involving soil, blood, and promises to fight for land and freedom.",
  "Thika's Blue Post Hotel was a colonial-era landmark where white settlers stopped for drinks on their way to the highlands.",
  "The phrase 'Harambee' -- meaning 'pull together' -- became Kenya's national motto under Kenyatta and symbolized collective self-reliance.",
  "J.M. Kariuki, a populist politician and Mau Mau veteran, was murdered in 1975. His body was found in the Ngong Hills. No one was ever convicted.",
  "The Norfolk Hotel in Nairobi was bombed in 1980 by a group believed to be connected to Palestinian militants. 20 people died.",
  "Wajir, in northeastern Kenya, has historically received less than 300mm of rainfall per year, making it one of the driest regions in the country.",
  "The 1992 Molo clashes were the first major episode of ethnic violence linked to multiparty politics in Kenya, killing hundreds in the Rift Valley.",
  "Koitalel arap Samoei, the Nandi Orkoiyot, led resistance against British rule and was killed by a colonial officer in 1905 during a supposed peace meeting.",
  "The Trans-Africa Highway, which was supposed to connect Mombasa to Lagos, remains incomplete in several sections across the continent.",
  "The term 'Silicon Savannah' was coined to describe Nairobi's growing tech ecosystem, which includes iHub, BRCK, and Ushahidi.",
  "Mekatilili wa Menza, a Giriama prophetess, led an uprising against British colonial rule on the coast in 1913 and was exiled to Kisii.",
  "The 2007-2008 post-election violence displaced over 600,000 people and killed more than 1,100, leading to the ICC trials.",
  "Kenyatta International Conference Centre (KICC) was the tallest building in Africa when it was completed in 1973.",
  "The Nyayo Era introduced a presidential queue voting system in 1988 where voters lined up behind their preferred candidate -- ending secret ballots.",
  "Matatu culture, with its blaring music and graffiti-covered buses, emerged in the 1980s as an informal but dominant public transport system.",
  "The Luo believed in a supreme creator called Nyasaye, and many cultural practices survived even after widespread Christian conversion.",
  "Gor Mahia FC, named after a legendary Luo medicine man, is Kenya's most successful football club with 20 league titles.",
  "The Likoni Ferry, connecting Mombasa Island to the South Coast, has been in operation since 1937 and remains a vital transport link.",
  "Eldoret, originally a farming town for white settlers, became a major athletics hub due to its high-altitude training conditions.",
  "The Sabaot, a Kalenjin sub-group in Mount Elgon, were embroiled in a brutal land conflict from 2006-2008 involving the Sabaot Land Defence Force.",
  "The Coast Province was the last region to join independent Kenya, with some leaders advocating for secession or federation with Zanzibar.",
  "The 1998 US Embassy bombing in Nairobi killed 213 people and injured over 4,000, most of them Kenyan civilians.",
  "Wangari Maathai was beaten and arrested multiple times by Moi's government for her activism before winning the Nobel Prize in 2004.",
  "Raila Odinga has run for president five times (1997, 2007, 2013, 2017, 2022) and has never officially won, though he disputes the 2007 and 2017 results.",
  "The Maasai lost over 60% of their land to colonial reserves and white settler farms between 1904 and 1911 through two controversial treaties.",
  "Kenyatta University was originally a teacher training college before becoming a full university in 1985.",
  "The Kipsigis practice of female circumcision was banned in the 1980s but continues in some communities as a rite of passage.",
  "The construction of the Standard Gauge Railway from Mombasa to Nairobi cost $3.8 billion and was funded and built by China.",
  "The term 'mzungu' comes from Swahili and originally meant 'one who wanders aimlessly,' referring to early European explorers.",
  "David Rudisha, the 800m world record holder, comes from a family of athletes -- his father won a silver medal in the 4x400m relay at the 1968 Olympics.",
  "Githeri Man became an internet sensation during the 2017 elections for queuing to vote while eating a bag of githeri (maize and beans).",
  "The Mombasa Republican Council, a secessionist group, was banned in 2010 but remains active in pushing for coastal autonomy.",
  "The phrase 'It's our time to eat' became infamous after John Githongo's exposé on Anglo Leasing corruption under Kibaki's government.",
  "Lupita Nyong'o, the Oscar-winning actress, was born in Mexico to Kenyan parents and raised in Nairobi before moving to the US for university."
];
